from domain.M3uEntity import M3uMovie, M3uEntity, M3uSerie


class M3uCollector:
    def collect(self, m3u_entity):
        pass


def collect(m3u_entities, collector: M3uCollector):
    return list(filter(None.__ne__, map(lambda entity: collector.collect(entity), m3u_entities)))


class M3uChannelCollector(M3uCollector):
    channel_id_dic = {"A&E": "a&e",
                      "A&E [Alter]": "a&e",
                      "A&E FHD": "a&e",
                      "A&E FHD H265": "a&e",
                      "A&E HD": "a&e",
                      "A&E HD [Alter]": "a&e",
                      "AMC": "amc",
                      "AMC [Alter]": "amc",
                      "AMC FHD": "amc",
                      "AMC FHD H265": "amc",
                      "AMC HD": "amc",
                      "AMC HD [Alter]": "amc",
                      "ANIMAL  PLANET FHD": "animal planet",
                      "ANIMAL PLANET": "animal planet",
                      "ANIMAL PLANET [Alter]": "animal planet",
                      "ANIMAL PLANET FHD H265": "animal planet",
                      "ANIMAL PLANET HD": "animal planet",
                      "ANIMAL PLANET HD [Alter]": "animal planet",
                      "ARTE 1": "arte 1",
                      "ARTE 1 [Alter]": "arte 1",
                      "ARTE 1 FHD": "arte 1",
                      "ARTE 1 HD": "arte 1",
                      "AXN": "axn",
                      "AXN [Alter]": "axn",
                      "AXN FHD": "axn",
                      "AXN FHD H265": "axn",
                      "AXN HD": "axn",
                      "AXN HD [Alter]": "axn",
                      "AXN HD LEG": "axn",
                      "AXN SD LEG": "axn",
                      "BABY TV": "baby tv",
                      "BABY TV [Alter]": "baby tv",
                      "BAND FHD H265": "band",
                      "BAND SP HD [Alter]": "band",
                      "BAND NEWS": "band news",
                      "BAND NEWS [Alter]": "band news",
                      "BAND NEWS FHD": "band news",
                      "BAND NEWS FHD H265": "band news",
                      "BAND NEWS HD": "band news",
                      "BAND SP [Alter]": "band",
                      "BAND SP FHD": "band",
                      "BAND SP HD": "band",
                      "BAND SPORTS FHD H265": "band sports",
                      "BIS": "bis",
                      "BIS [Alter]": "bis",
                      "BIS FHD H265": "bis",
                      "BIS FHD": "bis",
                      "BIS HD": "bis",
                      "Bis HD [Alter]": "bis",
                      "BOOMERANG": "boomerang",
                      "BOOMERANG  FHD": "boomerang",
                      "BOOMERANG [Alter]": "boomerang",
                      "BOOMERANG FHD H265": "boomerang",
                      "BOOMERANG HD": "boomerang",
                      "Boomerang HD [Alter]": "boomerang",
                      "BRASILEIRÃO SERIE C HD": "",
                      "CANAL BRASIL": "canal brasil",
                      "CANAL BRASIL [Alter]": "canal brasil",
                      "CANAL BRASIL FHD": "canal brasil",
                      "CANAL BRASIL HD [Alter]": "canal brasil",
                      "Canal Rural [Alter]": "",
                      "CANAL SONY": "sony",
                      "CANAL SONY FHD": "sony",
                      "CANAL SONY HD": "sony",
                      "Canal Sony HD [Alter]": "sony",
                      "CANAL SONY HD LEG": "sony",
                      "CANAL SONY SD LEG": "sony",
                      "CANÇÃO NOVA": "canção nova",
                      "CANÇÃO NOVA [Alter]": "canção nova",
                      "CARTOON NETWORK": "cartoon network",
                      "CARTOON NETWORK [Alter]": "cartoon network",
                      "CARTOON NETWORK FHD": "cartoon network",
                      "CARTOON NETWORK FHD H265": "cartoon network",
                      "CARTOON NETWORK HD": "cartoon network",
                      "Cartoon Network HD [Alter]": "cartoon network",
                      "CINEMAX": "cinemax",
                      "CINEMAX [Alter]": "cinemax",
                      "CINEMAX FHD": "cinemax",
                      "CINEMAX FHD H265": "cinemax",
                      "CINEMAX HD": "cinemax",
                      "Cinemax HD [Alter]": "cinemax",
                      "COMBATE": "combate",
                      "Combate [Alter]": "combate",
                      "COMBATE 4K": "combate",
                      "COMBATE FHD H265": "combate",
                      "COMBATE FHD": "combate",
                      "COMBATE HD": "combate",
                      "COMBATE HD [Alter]": "combate",
                      "COMEDY CENTRAL": "comedy central",
                      "Comedy Central [Alter]": "comedy central",
                      "COMEDY CENTRAL FHD": "comedy central",
                      "COMEDY CENTRAL FHD H265": "comedy central",
                      "COMEDY CENTRAL HD": "comedy central",
                      "Comedy Central HD [Alter]": "comedy central",
                      "Curta [Alter]": "",
                      "CURTA!": "",
                      "CURTA! FHD": "",
                      "CURTA! HD": "",
                      "DAZN HD - COPA SULAMERICANA": "",
                      "DISCOVERY CHANNEL": "discovery channel",
                      "Discovery Channel [Alter]": "discovery channel",
                      "DISCOVERY CHANNEL FHD H265": "discovery channel",
                      "DISCOVERY CHANNEL FHD": "discovery channel",
                      "DISCOVERY CHANNEL HD": "discovery channel",
                      "Discovery Channel HD [Alter]": "discovery channel",
                      "DISCOVERY CIVILIZATION": "discovery civilization",
                      "DISCOVERY CIVILIZATION FHD": "discovery civilization",
                      "DISCOVERY CIVILIZATION FHD H265": "discovery civilization",
                      "DISCOVERY CIVILIZATION HD": "discovery civilization",
                      "Discovery Civilization HD [Alter]": "discovery civilization",
                      "Discovery H&H [Alter]": "discovery home & health",
                      "DISCOVERY HOME & HEALTH": "discovery home & health",
                      "DISCOVERY HOME & HEALTH FHD": "discovery home & health",
                      "DISCOVERY HOME & HEALTH FHD H265": "discovery home & health",
                      "DISCOVERY HOME & HEALTH HD": "discovery home & health",
                      "Discovery Home & Helth HD [Alter]": "discovery home & health",
                      "DISCOVERY KIDS": "discovery kids",
                      "DISCOVERY KIDS FHD": "discovery kids",
                      "DISCOVERY KIDS FHD H265": "discovery kids",
                      "DISCOVERY KIDS HD": "discovery kids",
                      "Discovery Kids HD [Alter]": "discovery kids",
                      "DISCOVERY SCIENCE": "discovery science",
                      "DISCOVERY SCIENCE FHD": "discovery science",
                      "DISCOVERY SCIENCE FHD H265": "discovery science",
                      "DISCOVERY SCIENCE HD": "discovery science",
                      "Discovery Science HD [Alter]": "discovery science",
                      "DISCOVERY THEATER": "discovery theater",
                      "DISCOVERY THEATER FHD": "discovery theater",
                      "DISCOVERY THEATER FHD H265": "discovery theater",
                      "DISCOVERY THEATER HD": "discovery theater",
                      "Discovery Theater HD [Alter]": "discovery theater",
                      "DISCOVERY TURBO": "discovery turbo",
                      "Discovery Turbo [Alter]": "discovery turbo",
                      "DISCOVERY TURBO FHD": "discovery turbo",
                      "DISCOVERY TURBO FHD H265": "discovery turbo",
                      "DISCOVERY TURBO HD": "discovery turbo",
                      "Discovery Turbo HD [Alter]": "discovery turbo",
                      "DISCOVERY WORLD": "discovery world",
                      "DISCOVERY WORLD  HD": "discovery world",
                      "DISCOVERY WORLD FHD": "discovery world",
                      "DISCOVERY WORLD FHD H265": "discovery world",
                      "Discovery World HD [Alter]": "discovery world",
                      "Disney [Alter]": "disney channel",
                      "DISNEY CHANNEL": "disney channel",
                      "DISNEY CHANNEL FHD H265": "disney channel",
                      "DISNEY CHANNEL FHD": "disney channel",
                      "DISNEY CHANNEL HD": "disney channel",
                      "Disney Channel HD [Alter]": "disney channel",
                      "DISNEY JR": "disney jr",
                      "Disney JR [Alter]": "disney jr",
                      "DISNEY JR FHD": "disney jr",
                      "DISNEY JR FHD H265": "disney jr",
                      "DISNEY JR HD": "disney jr",
                      "DISNEY XD": "disney xd",
                      "Disney XD [Alter]": "disney xd",
                      "E!": "e!",
                      "E! [Alter]": "e!",
                      "E! FHD": "e!",
                      "E! HD": "e!",
                      "E! HD [Alter]": "e!",
                      "ESPN 2 FHD H265": "espn 2",
                      "ESPN BRASIL FHD H265": "espn brasil",
                      "ESPN FHD H265": "espn",
                      "FILM & ARTS": "film&arts",
                      "FISH TV": "fish tv",
                      "Fish TV [Alter]": "fish tv",
                      "FISH TV FHD": "fish tv",
                      "Fish TV HD [Alter]": "fish tv",
                      "FOOD NETWORK": "food network",
                      "Food Network [Alter]": "food network",
                      "FOOD NETWORK FHD": "food network",
                      "FOOD NETWORK FHD H265": "food network",
                      "FOOD NETWORK HD": "food network",
                      "Food Network HD [Alter]": "food network",
                      "FOX": "fox",
                      "Fox [Alter]": "fox",
                      "Fox 1 HD [Alter]": "fox",
                      "Fox Action HD [Alter]": "",
                      "FOX FHD H265": "fox",
                      "FOX FHD": "fox",
                      "FOX HD": "fox",
                      "Fox HD [Alter]": "fox",
                      "FOX HD LEG": "fox",
                      "FOX LIFE": "fox life",
                      "Fox Life [Alter]": "fox life",
                      "FOX LIFE FHD": "fox life",
                      "FOX LIFE FHD H265": "fox life",
                      "FOX LIFE HD": "fox life",
                      "Fox Life HD [Alter]": "fox life",
                      "FOX PREMIUM 1 FHD": "",
                      "Fox Premium 1 HD [Alter]": "",
                      "FOX PREMIUM 1": "",
                      "FOX PREMIUM 2 FHD": "",
                      "FOX PREMIUM 2 HD": "",
                      "FOX PREMIUM 2": "",
                      "FOX SD LEG": "fox",
                      "FOX SPORTS 2 FHD H265": "fox sports 2",
                      "FOX SPORTS FHD H265": "fox sports",
                      "FUTURA": "futura",
                      "FUTURA FHD": "futura",
                      "FUTURA HD": "futura",
                      "FX": "fx",
                      "FX [Alter]": "fx",
                      "FX FHD": "fx",
                      "FX FHD H265": "fx",
                      "FX HD": "fx",
                      "FX HD [Alter]": "fx",
                      "FX HD LEG": "fx",
                      "FX SD LEG": "fx",
                      "GLOBO INTERNACIONAL": "",
                      "GLOBO NEWS": "globonews",
                      "GLOBO NEWS [Alter]": "globonews",
                      "GLOBO NEWS FHD H265": "globonews",
                      "GLOBO NEWS FHD": "globonews",
                      "GLOBO NEWS HD": "globonews",
                      "GLOBO NEWS HD [Alter]": "globonews",
                      "GLOBO RPC CURITIBA": "globo rpc",
                      "GLOBO RPC CURITIBA FHD": "globo rpc",
                      "GLOBO RPC CURITIBA HD": "globo rpc",
                      "GLOBO RPC FOZ DO IGUACU FHD": "globo rpc",
                      "GLOBO RPC FOZ DO IGUACU HD": "globo rpc",
                      "GLOBO RPC FOZ DO IGUACU SD": "globo rpc",
                      "GLOOB": "gloob",
                      "GLOOB [Alter]": "gloob",
                      "GLOOB FHD": "gloob",
                      "GLOOB HD": "gloob",
                      "Gloob HD [Alter]": "gloob",
                      "GLOOBINHO": "gloobinho",
                      "GLOOBINHO FHD": "gloobinho",
                      "GLOOBINHO FHD H265": "gloobinho",
                      "GLOOBINHO HD": "gloobinho",
                      "GNT": "gnt",
                      "GNT [Alter]": "gnt",
                      "GNT FHD": "gnt",
                      "GNT FHD H265": "gnt",
                      "GNT HD": "gnt",
                      "GNT HD [Alter]": "gnt",
                      "GOSPEL CARTOON": "",
                      "GOSPEL MOVIES TELEVISION": "",
                      "GOSPEL MUSIC TELEVISION": "",
                      "H2": "history 2",
                      "H2 FHD": "history 2",
                      "H2 FHD H265": "history 2",
                      "H2 HD": "history 2",
                      "HBO": "hbo",
                      "HBO [Alter]": "hbo",
                      "HBO 2": "hbo 2",
                      "HBO 2 [Alter]": "hbo 2",
                      "HBO 2 FHD H265": "hbo 2",
                      "HBO 2 FHD": "hbo 2",
                      "HBO 2 HD": "hbo 2",
                      "HBO 2 HD [Alter]": "hbo 2",
                      "HBO FAMILY": "hbo family",
                      "HBO Family [Alter]": "hbo family",
                      "HBO FAMILY FHD": "hbo family",
                      "HBO FAMILY FHD H265": "hbo family",
                      "HBO FAMILY HD": "hbo family",
                      "HBO Family HD [Alter]": "hbo family",
                      "HBO FHD H265": "hbo",
                      "HBO FHD": "hbo",
                      "HBO HD": "hbo",
                      "HBO HD LEG": "hbo",
                      "HBO PLUS": "hbo plus",
                      "HBO Plus [Alter]": "hbo plus",
                      "HBO PLUS FHD": "hbo plus",
                      "HBO PLUS FHD H265": "hbo plus",
                      "HBO PLUS HD": "hbo plus",
                      "HBO Plus HD [Alter]": "hbo plus",
                      "HBO PLUS HD LEG": "hbo plus",
                      "HBO PLUS SD LEG": "hbo plus",
                      "HBO SD LEG": "hbo",
                      "HBO SIGNATURE": "hbo signature",
                      "HBO SIGNATURE [Alter]": "hbo signature",
                      "HBO SIGNATURE FHD": "hbo signature",
                      "HBO SIGNATURE FHD H265": "hbo signature",
                      "HBO SIGNATURE HD": "hbo signature",
                      "HBO Signature HD [Alter]": "hbo signature",
                      "HISTORY": "history",
                      "History [Alter]": "history",
                      "History 2 [Alter]": "history 2",
                      "History 2 HD [Alter]": "history 2",
                      "HISTORY FHD": "history",
                      "HISTORY HD": "history",
                      "History HD [Alter]": "history",
                      "HIT TV": "",
                      "ideal TV [Alter]": "",
                      "INVESTIGAÇÃO DISCOVERY": "investigacaodiscovery",
                      "INVESTIGAÇÃO DISCOVERY [Alter]": "investigacaodiscovery",
                      "INVESTIGAÇÃO DISCOVERY FHD H265": "investigacaodiscovery",
                      "INVESTIGAÇÃO DISCOVERY HD": "investigacaodiscovery",
                      "INVESTIGAÇÃO DISCOVERY HD [Alter]": "investigacaodiscovery",
                      "INVESTIGATION DISCOVERY FHD": "investigacaodiscovery",
                      "ISat [Alter]": "",
                      "Life Time [Alter]": "lifetime",
                      "LIFETIME": "lifetime",
                      "LIFETIME FHD": "lifetime",
                      "LIFETIME FHD H265": "lifetime",
                      "LIFETIME HD": "lifetime",
                      "MAIS GLOBOSAT": "mais globosat",
                      "MAIS GLOBOSAT FHD": "mais globosat",
                      "MAIS GLOBOSAT HD": "mais globosat",
                      "MAX": "max",
                      "Max [Alter]": "max",
                      "MAX FHD": "max",
                      "MAX FHD H265": "max",
                      "MAX HD": "max",
                      "Max HD [Alter]": "max",
                      "MAX PRIME": "max prime",
                      "Max Prime [Alter]": "max prime",
                      "MAX PRIME FHD": "max prime",
                      "MAX PRIME FHD H265": "max prime",
                      "MAX PRIME HD": "max prime",
                      "Max Prime HD [Alter]": "max prime",
                      "MAX PRIME SD LEG": "max prime",
                      "MAX SD LEG": "max",
                      "MAX UP": "max up",
                      "Max UP [Alter]": "max up",
                      "MAX UP FHD": "max up",
                      "MAX UP FHD H265": "max up",
                      "MAX UP HD": "max up",
                      "MAX UP HD LEG": "max up",
                      "MAX UP SD LEG": "max up",
                      "MEGAPIX": "megapix",
                      "Megapix [Alter]": "megapix",
                      "MEGAPIX FHD": "megapix",
                      "MEGAPIX FHD H265": "megapix",
                      "MEGAPIX HD": "megapix",
                      "Megapix HD [Alter]": "megapix",
                      "MEGAPIX HD LEG": "megapix",
                      "MEGAPIX SD LEG": "megapix",
                      "MTV": "mtv",
                      "MTV [Alter]": "mtv",
                      "MTV FHD": "mtv",
                      "MTV FHD H265": "mtv",
                      "MTV HD": "mtv",
                      "MTV HD [Alter]": "mtv",
                      "MTV LIVE FHD": "mtv live",
                      "MTV LIVE HD": "mtv live",
                      "MTV LIVE": "mtv live",
                      "MULTISHOW": "multishow",
                      "Multishow [Alter]": "multishow",
                      "MULTISHOW FHD": "multishow",
                      "MULTISHOW FHD H265": "multishow",
                      "MULTISHOW HD": "multishow",
                      "Multishow HD [Alter]": "multishow",
                      "MUSIC BOX BRASIL": "music box brazil",
                      "Music Box Brasil [Alter]": "music box brazil",
                      "MUSIC BOX BRASIL FHD": "music box brazil",
                      "MUSIC BOX BRASIL HD": "music box brazil",
                      "NAT GEO": "natgeo",
                      "NAT GEO FHD": "natgeo",
                      "NAT GEO HD": "natgeo",
                      "NAT GEO KIDS": "natgeo kids",
                      "NAT GEO KIDS FHD": "natgeo kids",
                      "NAT GEO KIDS HD": "natgeo kids",
                      "NAT GEO WILD": "natgeo wild",
                      "NAT GEO WILD FHD": "natgeo wild",
                      "NAT GEO WILD HD": "natgeo wild",
                      "NatGeo [Alter]": "natgeo",
                      "NATGEO FHD H265": "natgeo",
                      "NatGeo HD [Alter]": "natgeo",
                      "NatGeo Kids [Alter]": "natgeo kids",
                      "NATGEO KIDS FHD H265": "natgeo kids",
                      "NatGeo Kids HD [Alter]": "natgeo kids",
                      "NatGeo Wild [Alter]": "natgeo wild",
                      "NATGEO WILD FHD H265": "natgeo wild",
                      "NatGeo Wild HD [Alter]": "natgeo wild",
                      "NBR": "nbr",
                      "NBR [Alter]": "nbr",
                      "NHK WORLD HD": "nhk world premium",
                      "NICK FHD H265": "nick jr",
                      "NICK JR": "nick jr",
                      "Nick JR [Alter]": "nick jr",
                      "NICK JR FHD": "nick jr",
                      "NICK JR FHD H265": "nick jr",
                      "NICK JR HD": "nick jr",
                      "Nick JR HD [Alter]": "nick jr",
                      "NICKELODEN": "nickelodeon",
                      "Nickelodeon [Alter]": "nickelodeon",
                      "NICKELODEON FHD": "nickelodeon",
                      "NICKELODEON HD": "nickelodeon",
                      "Nickelodeon HD [Alter]": "nickelodeon",
                      "NOVO TEMPO": "",
                      "OFF": "off",
                      "OFF [Alter]": "off",
                      "OFF FHD": "off",
                      "OFF HD": "off",
                      "OFF HD [Alter]": "off",
                      "PARAMOUNT CHANNEL": "paramount",
                      "PARAMOUNT CHANNEL  [Alter]": "paramount",
                      "PARAMOUNT CHANNEL FHD": "paramount",
                      "PARAMOUNT CHANNEL FHD H265": "paramount",
                      "PARAMOUNT CHANNEL HD": "paramount",
                      "PARAMOUNT CHANNEL HD [Alter]": "paramount",
                      "Play Tv [Alter]": "play tv",
                      "PLAYBOY": "playboy",
                      "PLAYBOY [Alter]": "playboy",
                      "PLAYBOY FHD": "playboy",
                      "PLAYBOY HD": "playboy",
                      "PLAYBOY HD [Alter]": "playboy",
                      "PLAYKIDS FHD": "",
                      "PLAYKIDS HD": "",
                      "PLAYKIDS": "",
                      "POWER COUPLE BRASIL HD": "",
                      "POWER COUPLE BRASIL FHD": "",
                      "PREMIERE 2 FHD H265": "premiere 2",
                      "PREMIERE 3 FHD H265": "premiere 3",
                      "PREMIERE 4 FHD H265": "premiere 4",
                      "PREMIERE 5 FHD H265": "premiere 5",
                      "PREMIERE 7 FHD H265": "premiere 7",
                      "Premiere Clubes 4K UHD": "premiere clubes",
                      "PREMIERE CLUBES FHD H265": "premiere clubes",
                      "PRIME BOX BRASIL": "prime box brazil",
                      "PRIME BOX BRASIL [Alter]": "prime box brazil",
                      "PRIME BOX BRASIL FHD": "prime box brazil",
                      "PRIME BOX BRASIL HD": "prime box brazil",
                      "RECORD [Alter]": "record",
                      "RECORD FHD H265S": "record",
                      "RECORD HD": "record",
                      "RECORD HD [Alter]": "record",
                      "RECORD NEWS": "record news",
                      "RECORD NEWS [Alter]": "record news",
                      "RECORD NEWS FHD": "record news",
                      "RECORD NEWS HD": "record news",
                      "REDE GOSPEL": "",
                      "REDE SUPER": "",
                      "REDE TV": "rede tv",
                      "REDE TV [Alter]": "rede tv",
                      "REDE TV FHD": "rede tv",
                      "REDE TV HD": "rede tv",
                      "REDE TV HD [Alter]": "rede tv",
                      "REDE VIDA": "rede vida",
                      "REDE VIDA FHD": "rede vida",
                      "REDE VIDA HD": "rede vida",
                      "SBT": "sbt",
                      "SBT [Alter]": "sbt",
                      "SBT FHD": "sbt",
                      "SBT HD": "sbt",
                      "SBT HD [Alter]": "sbt",
                      "SEXY HOT FHD": "sexy hot",
                      "SEXTREME": "sextreme",
                      "SEXTREME [Alter]": "sextreme",
                      "SEXY HOT": "sexy hot",
                      "SEXY HOT [Alter]": "sexy hot",
                      "SIC Internacional [Alter]": "sic international",
                      "SMITHSONIAN CHANNEL FHD": "smithsonian",
                      "SMITHSONIAN CHANNEL HD": "smithsonian",
                      "SMITHSONIAN CHANNEL": "smithsonian",
                      "Sony [Alter]": "sony",
                      "SPACE": "space",
                      "SPACE [Alter]": "space",
                      "SPACE FHD": "space",
                      "SPACE FHD H265": "space",
                      "SPACE HD": "space",
                      "Space HD [Alter]": "space",
                      "SPACE HD LEG": "space",
                      "SPACE SD LEG": "space",
                      "SPORTV 2 FHD H265": "sportv 2",
                      "SPORTV 3 FHD H265": "sportv 3",
                      "SPORTV 4K": "sportv",
                      "SPORTV FHD H265": "sportv",
                      "Studio Universal [Alter]": "studio universal",
                      "STUDIO UNIVERSAL FHD": "studio universal",
                      "STUDIO UNIVERSAL HD": "studio universal",
                      "STUDIO UNIVERSAL": "studio universal",
                      "SYFY": "syfy",
                      "Syfy [Alter]": "syfy",
                      "SYFY FHD": "syfy",
                      "SYFY HD": "syfy",
                      "TBS [Alter]": "tbs",
                      "TBS FHD": "tbs",
                      "TBS FHD H265": "tbs",
                      "TBS HD": "tbs",
                      "TBS HD [Alter]": "tbs",
                      "TBS": "tbs",
                      "TCM [Alter]": "tcm",
                      "TCM": "tcm",
                      "TELECINE ACTION": "telecine action",
                      "TELECINE ACTION [Alter]": "telecine action",
                      "TELECINE ACTION FHD H265": "telecine action",
                      "TELECINE ACTION FULLHD": "telecine action",
                      "TELECINE ACTION HD": "telecine action",
                      "TELECINE ACTION HD [Alter]": "telecine action",
                      "TELECINE ACTION HD LEG": "telecine action",
                      "TELECINE ACTION SD LEG": "telecine action",
                      "TELECINE CULT": "telecine cult",
                      "TELECINE CULT [Alter]": "telecine cult",
                      "TELECINE CULT FHD": "telecine cult",
                      "TELECINE CULT FHD H265": "telecine cult",
                      "TELECINE CULT HD": "telecine cult",
                      "TELECINE CULT HD [Alter]": "telecine cult",
                      "TELECINE FUN": "telecine fun",
                      "TELECINE FUN [Alter]": "telecine fun",
                      "TELECINE FUN FHD H265": "telecine fun",
                      "TELECINE FUN FULLHD": "telecine fun",
                      "TELECINE FUN HD": "telecine fun",
                      "TELECINE FUN HD [Alter]": "telecine fun",
                      "TELECINE FUN HD LEG": "telecine fun",
                      "TELECINE FUN SD LEG": "telecine fun",
                      "TELECINE PIPOCA": "telecine pipoca",
                      "TELECINE PIPOCA [Alter]": "telecine pipoca",
                      "TELECINE PIPOCA FHD H265": "telecine pipoca",
                      "TELECINE PIPOCA FULLHD": "telecine pipoca",
                      "TELECINE PIPOCA HD": "telecine pipoca",
                      "TELECINE PIPOCA HD [Alter]": "telecine pipoca",
                      "TELECINE PIPOCA HD LEG": "telecine pipoca",
                      "TELECINE PIPOCA SD LEG": "telecine pipoca",
                      "TELECINE PREMIUM": "telecine premium",
                      "TELECINE PREMIUM [Alter]": "telecine premium",
                      "TELECINE PREMIUM FHD H265": "telecine premium",
                      "TELECINE PREMIUM FULLHD": "telecine premium",
                      "TELECINE PREMIUM HD": "telecine premium",
                      "TELECINE PREMIUM HD [Alter]": "telecine premium",
                      "TELECINE PREMIUM HD LEG": "telecine premium",
                      "TELECINE PREMIUM SD LEG*": "telecine premium",
                      "TELECINE TOUCH": "telecine touch",
                      "TELECINE TOUCH [Alter]": "telecine touch",
                      "TELECINE TOUCH FHD H265": "telecine touch",
                      "TELECINE TOUCH FULLHD": "telecine touch",
                      "TELECINE TOUCH HD": "telecine touch",
                      "TELECINE TOUCH HD [Alter]": "telecine touch",
                      "TELECINE TOUCH HD LEG": "telecine touch",
                      "TELECINE TOUCH SD LEG": "telecine touch",
                      "TERRA VIVA": "",
                      "Terra Viva [Alter]": "",
                      "THE HISTORY FHD H265": "history",
                      "TLC [Alter]": "tlc",
                      "TLC FHD": "tlc",
                      "TLC HD": "tlc",
                      "TLC HD [Alter]": "tlc",
                      "TLC": "tlc",
                      "TNT": "tnt",
                      "TNT [Alter]": "tnt",
                      "TNT FHD": "tnt",
                      "TNT FHD H265": "tnt",
                      "TNT HD": "tnt",
                      "TNT HD [Alter]": "tnt",
                      "TNT HD LEG": "tnt",
                      "TNT SD LEG": "tnt",
                      "TNT SERIES": "tnt series",
                      "TNT SERIES [Alter]": "tnt series",
                      "TNT SERIES FHD": "tnt series",
                      "TNT SERIES FHD H265": "tnt series",
                      "TNT SERIES HD": "tnt series",
                      "TNT Series HD [Alter]": "tnt series",
                      "TNT SERIES HD LEG": "tnt series",
                      "TNT SERIES SD LEG": "tnt series",
                      "TOOCAST [Alter]": "tooncast",
                      "TOONCAST": "tooncast",
                      "TOP TV": "",
                      "Tru TV [Alter]": "tru tv",
                      "TruTV": "tru tv",
                      "TRUTV FHD": "tru tv",
                      "TruTV HD": "tru tv",
                      "TV APARECIDA": "tv aparecida",
                      "TV APARECIDA [Alter]": "tv aparecida",
                      "TV CULTURA FHD": "cultura",
                      "TV CULTURA HD": "cultura",
                      "TV CULTURA": "cultura",
                      "TV Futura [Alter]": "futura",
                      "TV RA TIM BUM [Alter]": "tv ra tim bum",
                      "TV RA TIM BUM FHD": "tv ra tim bum",
                      "TV RA TIM BUM HD": "tv ra tim bum",
                      "TV RA TIM BUM": "tv ra tim bum",
                      "UNIVERSAL CHANNEL": "universal",
                      "UNIVERSAL CHANNEL [Alter]": "universal",
                      "UNIVERSAL CHANNEL FHD": "warner channel",
                      "UNIVERSAL CHANNEL FHD H265": "universal",
                      "UNIVERSAL CHANNEL HD": "universal",
                      "Universal Channel HD [Alter]": "universal",
                      "VENUS": "venus",
                      "VENUS [Alter]": "venus",
                      "VH1 FHD": "vh1",
                      "VH1 HD": "vh1",
                      "VH1 HD [Alter]": "vh1",
                      "VH1 Mega Hits [Alter]": "vh1 megahits",
                      "VH1 MEGA HITS": "vh1 megahits",
                      "VH1": "vh1",
                      "VIVA": "viva",
                      "VIVA FHD H265": "viva",
                      "VIVA FULLHD": "viva",
                      "VIVA HD": "viva",
                      "Viva HD [Alter]": "viva",
                      "WARNER CHANNEL": "warner",
                      "Warner Channel [Alter]": "warner",
                      "WARNER CHANNEL FHD H265": "warner",
                      "WARNER CHANNEL HD": "warner",
                      "WARNER FHD": "warner",
                      "Warner HD [Alter]": "warner",
                      "WARNER HD LEG": "warner",
                      "WARNER SD LEG": "warner",
                      "WOOHOO": "woohoo",
                      "Woohoo [Alter]": "woohoo",
                      "WOOHOO FHD": "woohoo",
                      "WOOHOO HD": "woohoo",
                      "Woohoo HD [Alter]": "woohoo"
                      }

    def collect(self, m3u_entity):
        group = m3u_entity.tvg_group
        if group.__contains__("Canais:") and not (group.__contains__("Adultos")):
            tvg_id = self.channel_id_dic.get(m3u_entity.tvg_name)
            if tvg_id:
                m3u_entity.tvg_id = tvg_id
                return m3u_entity

    # def getPossibleKeyMatches(self, key, matcher):
    #     if key[0:3].casefold() in matcher.replace(' ', '').casefold():
    #         return True
    #     else:
    #         return False


class M3uMovieCollector(M3uCollector):
    def collect(self, m3u_entity):
        group = m3u_entity.tvg_group
        if (group.__contains__("Filme:") or group.__contains__("Coleção: ")) and not (group.__contains__("Adultos")):
            return M3uMovie(m3u_entity.line, m3u_entity.link)


class M3uSeriesCollector(M3uCollector):
    def collect(self, m3u_entity):
        group = m3u_entity.tvg_group
        if group.__contains__("Série:") or group.__contains__("Serie:"):
            return M3uSerie(m3u_entity.line, m3u_entity.link)


class M3uRadioCollector(M3uCollector):
    def collect(self, m3u_entity):
        group = m3u_entity.tvg_group
        if group.__contains__("Rádios") or group.__contains__("Radios:"):
            return M3uEntity(m3u_entity.line, m3u_entity.link)


class M3uAdultCollector(M3uCollector):
    def collect(self, m3u_entity):
        group = m3u_entity.tvg_group
        if group.__contains__("Adultos"):
            if group.__contains__("Filme:"):
                return M3uMovie(m3u_entity.line, m3u_entity.link)
            else:
                return M3uEntity(m3u_entity.line, m3u_entity.link)


class M3uChannel24Collector(M3uCollector):
    def collect(self, m3u_entity):
        group = m3u_entity.tvg_group
        if group.__contains__("Canais: 24") and not (group.__contains__("Adultos")):
            return m3u_entity
